import hashlib
import io
import uuid
from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from httpx import ASGITransport, AsyncClient

from app.api.v1.documents import process_document
from app.dependencies import get_current_tenant_id
from app.db.session import get_db
from app.main import create_app
from app.services.chunking import TextChunk


TENANT_ID = str(uuid.uuid4())
FAKE_FILE_BYTES = b"Hello, this is a test document."
FAKE_FILENAME = "test.txt"
FAKE_CONTENT_HASH = hashlib.sha256(FAKE_FILE_BYTES).hexdigest()


def _make_file_upload(content: bytes = FAKE_FILE_BYTES, filename: str = FAKE_FILENAME):
    return {
        "files": {"file": (filename, io.BytesIO(content), "text/plain")},
    }


@pytest.fixture
def mock_db_session():
    """
    A mock AsyncSession.

    By default, scalar_one_or_none() returns None — simulates a new document
    (no duplicate found). Tests that need a duplicate override this directly.

    Why side_effect on add()?
      In real Postgres, the Document primary key is a UUID generated by Python's
      `default=uuid.uuid4` inside the ORM — but SQLAlchemy only calls that
      default when it builds the INSERT during flush(). Our mock never executes
      real SQL, so doc.id stays None. The side_effect on add() mimics the
      ORM by assigning a UUID at the moment the object is registered with the
      session, giving the route a valid doc.id to return in the 202 body.
    """
    session = AsyncMock()

    # Deduplication SELECT returns no existing document (new upload path)
    result = MagicMock()
    result.scalar_one_or_none.return_value = None
    session.execute = AsyncMock(return_value=result)

    # Simulate ORM UUID assignment that normally happens during flush.
    #
    # Why MagicMock (not AsyncMock) for add()?
    #   SQLAlchemy's AsyncSession.add() is SYNCHRONOUS — it just registers
    #   the object with the identity map; it doesn't touch the database.
    #   AsyncMock attributes are also AsyncMock by default, so calling
    #   async_mock.add(doc) without await returns a coroutine object but
    #   never executes the side_effect. Using MagicMock ensures the
    #   side_effect fires synchronously the moment add() is called.
    def _assign_id(obj):
        if hasattr(obj, "id") and obj.id is None:
            obj.id = uuid.uuid4()

    session.add = MagicMock(side_effect=_assign_id)

    session.flush = AsyncMock()

    return session


@pytest.fixture
def app_with_mock_db(mock_db_session):
    app = create_app()

    async def _mock_get_db():
        yield mock_db_session

    app.dependency_overrides[get_db] = _mock_get_db
    app.dependency_overrides[get_current_tenant_id] = lambda: uuid.UUID(TENANT_ID)
    yield app, mock_db_session
    app.dependency_overrides.clear()


@pytest.fixture
async def client(app_with_mock_db):
    app, _ = app_with_mock_db
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        yield ac


@pytest.fixture
async def client_and_db(app_with_mock_db):
    app, mock_db = app_with_mock_db
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        yield ac, mock_db


@pytest.mark.asyncio
@patch("app.api.v1.documents.process_document")
async def test_new_document_returns_202(mock_process, client):
    mock_process.return_value = None

    response = await client.post("/api/v1/documents/upload", **_make_file_upload())

    assert response.status_code == 202


@pytest.mark.asyncio
@patch("app.api.v1.documents.process_document")
async def test_new_document_response_body(mock_process, client):
    mock_process.return_value = None

    response = await client.post("/api/v1/documents/upload", **_make_file_upload())

    body = response.json()
    assert body["status"] == "processing"
    assert body["filename"] == FAKE_FILENAME
    # document_id is a UUID string — just check it parses
    uuid.UUID(body["document_id"])


@pytest.mark.asyncio
@patch("app.api.v1.documents.process_document")
async def test_new_document_commits_before_returning(mock_process, client_and_db):
    mock_process.return_value = None
    client, mock_db = client_and_db

    await client.post("/api/v1/documents/upload", **_make_file_upload())

    # commit() (not flush()) so the row is visible to the background task's separate session
    mock_db.commit.assert_called_once()


@pytest.mark.asyncio
@patch("app.api.v1.documents.process_document")
async def test_background_task_registered_for_new_document(mock_process, client):
    mock_process.return_value = None

    await client.post("/api/v1/documents/upload", **_make_file_upload())

    # The mock was called once — meaning BackgroundTasks ran it (synchronously in tests)
    mock_process.assert_called_once()
    call_kwargs = mock_process.call_args
    assert call_kwargs.args[1] == FAKE_FILE_BYTES
    assert call_kwargs.args[2] == FAKE_FILENAME


@pytest.mark.asyncio
@patch("app.api.v1.documents.process_document")
async def test_duplicate_document_returns_200(mock_process, client_and_db):
    mock_process.return_value = None
    client, mock_db = client_and_db

    # Make the deduplication SELECT return an existing document
    existing = MagicMock()
    existing.id = uuid.uuid4()
    existing.filename = FAKE_FILENAME
    result = MagicMock()
    result.scalar_one_or_none.return_value = existing
    mock_db.execute = AsyncMock(return_value=result)

    response = await client.post("/api/v1/documents/upload", **_make_file_upload())

    assert response.status_code == 200


@pytest.mark.asyncio
@patch("app.api.v1.documents.process_document")
async def test_duplicate_response_body(mock_process, client_and_db):
    mock_process.return_value = None
    client, mock_db = client_and_db

    existing_id = uuid.uuid4()
    existing = MagicMock()
    existing.id = existing_id
    existing.filename = FAKE_FILENAME
    result = MagicMock()
    result.scalar_one_or_none.return_value = existing
    mock_db.execute = AsyncMock(return_value=result)

    response = await client.post("/api/v1/documents/upload", **_make_file_upload())

    body = response.json()
    assert body["status"] == "already_exists"
    assert uuid.UUID(body["document_id"]) == existing_id


@pytest.mark.asyncio
@patch("app.api.v1.documents.process_document")
async def test_duplicate_does_not_queue_background_task(mock_process, client_and_db):
    mock_process.return_value = None
    client, mock_db = client_and_db

    existing = MagicMock()
    existing.id = uuid.uuid4()
    existing.filename = FAKE_FILENAME
    result = MagicMock()
    result.scalar_one_or_none.return_value = existing
    mock_db.execute = AsyncMock(return_value=result)

    await client.post("/api/v1/documents/upload", **_make_file_upload())

    mock_process.assert_not_called()


@pytest.mark.asyncio
async def test_empty_file_returns_400(client):
    response = await client.post(
        "/api/v1/documents/upload",
        **_make_file_upload(content=b""),
    )
    assert response.status_code == 400
    assert "empty" in response.json()["detail"].lower()


from app.api.v1.documents import _validate_file_magic


def test_validate_file_magic_accepts_valid_pdf():
    valid_pdf = b"%PDF-1.4 fake content"
    _validate_file_magic(valid_pdf, "document.pdf")  # must not raise


def test_validate_file_magic_accepts_valid_png():
    valid_png = b"\x89PNG\r\n\x1a\n fake png content"
    _validate_file_magic(valid_png, "image.png")  # must not raise


def test_validate_file_magic_rejects_pdf_with_wrong_magic():
    from fastapi import HTTPException
    png_bytes = b"\x89PNG\r\n\x1a\n fake png content"
    with pytest.raises(HTTPException) as exc_info:
        _validate_file_magic(png_bytes, "not_really.pdf")
    assert exc_info.value.status_code == 400
    assert ".pdf" in exc_info.value.detail


def test_validate_file_magic_rejects_non_utf8_txt():
    from fastapi import HTTPException
    binary_bytes = b"\xff\xfe\x00invalid binary data"
    with pytest.raises(HTTPException) as exc_info:
        _validate_file_magic(binary_bytes, "notes.txt")
    assert exc_info.value.status_code == 400


def _make_fake_chunks(n: int = 2) -> list[TextChunk]:
    return [
        TextChunk(chunk_index=i, char_start=i * 10, char_end=(i + 1) * 10, text=f"chunk {i}")
        for i in range(n)
    ]


FAKE_VECTORS = [[0.1] * 384, [0.2] * 384]


@pytest.fixture
def mock_async_session_local():
    """
    Context-manager mock for AsyncSessionLocal().

    process_document opens its own session (separate from the request session):
        async with AsyncSessionLocal() as db:
            ...

    We mock __aenter__ to return a mock session and __aexit__ to be a no-op.
    """
    mock_session = AsyncMock()

    fake_doc = MagicMock()
    mock_session.get = AsyncMock(return_value=fake_doc)

    # add_all() is synchronous in AsyncSession (same reason as add() above)
    mock_session.add_all = MagicMock()

    ctx = MagicMock()
    ctx.__aenter__ = AsyncMock(return_value=mock_session)
    ctx.__aexit__ = AsyncMock(return_value=False)

    return ctx, mock_session, fake_doc


@pytest.mark.asyncio
async def test_process_document_happy_path(mock_async_session_local):
    """
    Happy path: extract → chunk → embed → store chunks → update chunk_count → commit.

    Note: _extraction_service.extract is called via asyncio.to_thread (synchronous).
    Mocking the method directly works because to_thread calls it in a thread pool
    and returns its return value. add() is synchronous in AsyncSession — using
    MagicMock (not AsyncMock) for add_all() ensures the side_effect fires correctly.
    """
    ctx, mock_session, fake_doc = mock_async_session_local
    fake_chunks = _make_fake_chunks(2)

    with (
        patch("app.api.v1.documents.AsyncSessionLocal", return_value=ctx),
        patch("app.api.v1.documents._extraction_service") as mock_ext,
        patch("app.api.v1.documents._ner_service") as mock_ner,
        patch("app.api.v1.documents._chunking_service") as mock_chunk,
        patch("app.api.v1.documents._embedding_service") as mock_embed,
    ):
        mock_ext.extract.return_value = "extracted text"
        mock_ner.extract_entities = AsyncMock(return_value={"PERSON": ["Test Person"]})
        mock_chunk.chunk.return_value = fake_chunks
        mock_embed.embed_texts = AsyncMock(return_value=FAKE_VECTORS)

        await process_document(uuid.uuid4(), FAKE_FILE_BYTES, FAKE_FILENAME, uuid.uuid4())

    mock_session.add_all.assert_called_once()
    stored_chunks = mock_session.add_all.call_args.args[0]
    assert len(stored_chunks) == 2
    assert fake_doc.chunk_count == 2
    assert fake_doc.entities is not None
    mock_session.commit.assert_called_once()


@pytest.mark.asyncio
async def test_process_document_rollback_on_error(mock_async_session_local):
    ctx, mock_session, _ = mock_async_session_local

    with (
        patch("app.api.v1.documents.AsyncSessionLocal", return_value=ctx),
        patch("app.api.v1.documents._extraction_service") as mock_ext,
        patch("app.api.v1.documents._ner_service"),
        patch("app.api.v1.documents._chunking_service"),
        patch("app.api.v1.documents._embedding_service"),
    ):
        mock_ext.extract.side_effect = RuntimeError("extraction failed")

        doc_id = uuid.uuid4()
        tenant_id = uuid.uuid4()

        # Must not raise
        await process_document(doc_id, FAKE_FILE_BYTES, FAKE_FILENAME, tenant_id)

    mock_session.rollback.assert_called_once()
    mock_session.commit.assert_not_called()


@pytest.mark.asyncio
async def test_process_document_does_not_raise_on_any_exception(mock_async_session_local):
    ctx, mock_session, _ = mock_async_session_local

    with (
        patch("app.api.v1.documents.AsyncSessionLocal", return_value=ctx),
        patch("app.api.v1.documents._extraction_service") as mock_ext,
        patch("app.api.v1.documents._ner_service"),
        patch("app.api.v1.documents._chunking_service"),
        patch("app.api.v1.documents._embedding_service"),
    ):
        mock_ext.extract.side_effect = MemoryError("out of memory")

        await process_document(uuid.uuid4(), FAKE_FILE_BYTES, FAKE_FILENAME, uuid.uuid4())


FAKE_CREATED_AT = datetime(2026, 3, 7, 12, 0, 0, tzinfo=timezone.utc)


def _make_fake_doc(
    document_id: uuid.UUID | None = None,
    tenant_id: str | None = None,
    chunk_count: int = 5,
) -> MagicMock:
    doc = MagicMock()
    doc.id = document_id or uuid.uuid4()
    doc.tenant_id = uuid.UUID(tenant_id or TENANT_ID)
    doc.filename = "test.txt"
    doc.content_type = "text/plain"
    doc.chunk_count = chunk_count
    doc.created_at = FAKE_CREATED_AT
    doc.entities = {"PERSON": ["John Smith"], "ORG": ["Acme Corp"]}
    return doc


def _make_count_result(n: int) -> MagicMock:
    result = MagicMock()
    result.scalar_one.return_value = n
    return result


def _make_list_result(docs: list) -> MagicMock:
    result = MagicMock()
    scalars = MagicMock()
    scalars.all.return_value = docs
    result.scalars.return_value = scalars
    return result


@pytest.mark.asyncio
async def test_get_document_returns_200(client_and_db):
    client, mock_db = client_and_db
    doc = _make_fake_doc()
    mock_db.get = AsyncMock(return_value=doc)

    response = await client.get(
        f"/api/v1/documents/{doc.id}",
    )
    assert response.status_code == 200


@pytest.mark.asyncio
async def test_get_document_response_shape(client_and_db):
    client, mock_db = client_and_db
    doc_id = uuid.uuid4()
    doc = _make_fake_doc(document_id=doc_id, chunk_count=3)
    mock_db.get = AsyncMock(return_value=doc)

    response = await client.get(
        f"/api/v1/documents/{doc_id}",
    )
    body = response.json()

    assert uuid.UUID(body["document_id"]) == doc_id
    assert body["filename"] == "test.txt"
    assert body["content_type"] == "text/plain"
    assert body["chunk_count"] == 3
    assert body["status"] == "ready"
    assert "created_at" in body
    assert "entities" in body


@pytest.mark.asyncio
async def test_get_document_status_processing(client_and_db):
    client, mock_db = client_and_db
    doc = _make_fake_doc(chunk_count=0)
    mock_db.get = AsyncMock(return_value=doc)

    response = await client.get(
        f"/api/v1/documents/{doc.id}",
    )
    assert response.json()["status"] == "processing"


@pytest.mark.asyncio
async def test_get_document_status_ready(client_and_db):
    client, mock_db = client_and_db
    doc = _make_fake_doc(chunk_count=7)
    mock_db.get = AsyncMock(return_value=doc)

    response = await client.get(
        f"/api/v1/documents/{doc.id}",
    )
    assert response.json()["status"] == "ready"


@pytest.mark.asyncio
async def test_get_document_not_found_returns_404(client_and_db):
    client, mock_db = client_and_db
    mock_db.get = AsyncMock(return_value=None)

    response = await client.get(
        f"/api/v1/documents/{uuid.uuid4()}",
    )
    assert response.status_code == 404


@pytest.mark.asyncio
async def test_get_document_wrong_tenant_returns_404(client_and_db):
    """Document exists but belongs to a different tenant → 404, not 403."""
    client, mock_db = client_and_db
    other_tenant_id = str(uuid.uuid4())
    doc = _make_fake_doc(tenant_id=other_tenant_id)
    mock_db.get = AsyncMock(return_value=doc)

    response = await client.get(
        f"/api/v1/documents/{doc.id}",
    )
    assert response.status_code == 404


@pytest.mark.asyncio
async def test_delete_document_returns_204(client_and_db):
    client, mock_db = client_and_db
    doc = _make_fake_doc()
    mock_db.get = AsyncMock(return_value=doc)

    response = await client.delete(
        f"/api/v1/documents/{doc.id}",
    )
    assert response.status_code == 204


@pytest.mark.asyncio
async def test_delete_document_not_found_returns_404(client_and_db):
    client, mock_db = client_and_db
    mock_db.get = AsyncMock(return_value=None)

    response = await client.delete(
        f"/api/v1/documents/{uuid.uuid4()}",
    )
    assert response.status_code == 404


@pytest.mark.asyncio
async def test_delete_calls_db_delete_and_commit(client_and_db):
    client, mock_db = client_and_db
    doc = _make_fake_doc()
    mock_db.get = AsyncMock(return_value=doc)

    await client.delete(
        f"/api/v1/documents/{doc.id}",
    )

    mock_db.delete.assert_called_once_with(doc)
    mock_db.commit.assert_called_once()


@pytest.mark.asyncio
async def test_list_documents_returns_200(client_and_db):
    client, mock_db = client_and_db
    mock_db.execute = AsyncMock(side_effect=[
        _make_count_result(0),
        _make_list_result([]),
    ])

    response = await client.get(
        "/api/v1/documents/",
    )
    assert response.status_code == 200


@pytest.mark.asyncio
async def test_list_documents_empty(client_and_db):
    client, mock_db = client_and_db
    mock_db.execute = AsyncMock(side_effect=[
        _make_count_result(0),
        _make_list_result([]),
    ])

    response = await client.get(
        "/api/v1/documents/",
    )
    body = response.json()
    assert body["total"] == 0
    assert body["results"] == []


@pytest.mark.asyncio
async def test_list_documents_response_shape(client_and_db):
    client, mock_db = client_and_db
    doc = _make_fake_doc(chunk_count=3)
    mock_db.execute = AsyncMock(side_effect=[
        _make_count_result(1),
        _make_list_result([doc]),
    ])

    response = await client.get(
        "/api/v1/documents/?page=1&page_size=10",
    )
    body = response.json()

    assert body["total"] == 1
    assert body["page"] == 1
    assert body["page_size"] == 10
    assert len(body["results"]) == 1
    assert body["results"][0]["status"] == "ready"


@pytest.mark.asyncio
async def test_list_documents_pagination_defaults(client_and_db):
    client, mock_db = client_and_db
    mock_db.execute = AsyncMock(side_effect=[
        _make_count_result(0),
        _make_list_result([]),
    ])

    response = await client.get(
        "/api/v1/documents/",
    )
    body = response.json()
    assert body["page"] == 1
    assert body["page_size"] == 10
